name: muslim_today
description: A new Flutter project.

version: 1.3.5+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adhan: ^2.0.0-nullsafety.2
  android_intent: ^2.0.2
  animated_splash_screen: ^1.2.0
  apple_sign_in_safety: ^0.0.6
  audioplayers: ^0.20.1
  auto_size_text: ^3.0.0
  bottom_navy_bar: ^6.0.0
  card_swiper: ^2.0.3
  change_app_package_name: ^1.0.0
  cloud_firestore: ^3.1.10
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.4
  device_preview: ^1.1.0
  device_preview_screenshot: ^1.0.0
  dotted_border: ^2.0.0+2
  easy_localization: ^3.0.0
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.4.0
  flutter_native_splash: ^2.1.2+1
  flutter_overboard: ^3.1.1
  flutter_qiblah: ^2.0.2
  flutter_svg: ^1.0.3
  flutter_typeahead: ^3.2.4
  flutter_vibrate: ^1.3.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  get: ^4.6.1
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.4
  hijri: ^3.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  loading_indicator: ^3.0.3
  location: ^4.3.0
  package_info: ^2.0.2
  package_info_plus: ^1.4.0
  path: ^1.8.0
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  provider: ^6.0.2
  quran: ^1.1.2
  rxdart: ^0.27.3
  share: ^2.0.4
  shared_preferences: ^2.0.13
  shared_preferences_web: ^2.0.3
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.2.0
  sleek_circular_slider: ^2.0.1
  swipe: ^0.0.1
  syncfusion_flutter_gauges: ^20.1.50
  url_launcher: ^6.0.20

dependency_overrides:
  geolocator: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/

  fonts:
    - family: Al-Qalam
      fonts:
        - asset: fonts/Al-Qalam.ttf
    - family: Quran-Font
      fonts:
        - asset: fonts/Quran-Font.ttf
    - family: Noore
      fonts:
        - asset: fonts/Noore.ttf
    - family: Kurale
      fonts:
        - asset: fonts/Kurale.otf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

flutter_native_splash:
  color: "#ffffff"
  image_path: assets/img/app_icon.png
