name: muslim_today
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.4+1


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  font_awesome_flutter: ^10.1.0
  loading_indicator: ^3.0.3
  shared_preferences: ^2.0.13
  shared_preferences_web: ^2.0.3
  get: ^4.6.1
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  provider: ^6.0.2
  cloud_firestore: ^3.1.10
  animated_splash_screen: ^1.2.0
  google_sign_in: ^5.2.4
  flutter_native_splash: ^2.1.2+1
  flutter_bloc: ^8.0.1
  flutter_vibrate: ^1.3.0
  connectivity: ^3.0.6
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  permission_handler: ^9.2.0
  location: ^4.3.0
  android_intent: ^2.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  package_info_plus: ^1.4.0
  shimmer: ^2.0.0
  flutter_overboard: ^3.1.1
  share: ^2.0.4
  url_launcher: ^6.0.20
  flutter_local_notifications: ^9.4.0
  easy_localization: ^3.0.0
  rxdart: ^0.27.3
  flutter_typeahead: ^3.2.4
  flutter_svg: ^1.0.3
  dotted_border: ^2.0.0+2
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  hijri: ^3.0.0
  adhan: ^2.0.0-nullsafety.2
  quran: ^1.1.2
  audioplayers: ^0.20.1
  bottom_navy_bar: ^6.0.0
  flutter_qiblah: ^2.0.2
  card_swiper: ^2.0.3
  path: ^1.8.0
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_gauges: ^20.1.50
  swipe: ^0.0.1
  package_info: ^2.0.2

dependency_overrides:
  geolocator: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/

  fonts:
    - family: Al-Qalam
      fonts:
        - asset: fonts/Al-Qalam.ttf
    - family: Quran-Font
      fonts:
        - asset: fonts/Quran-Font.ttf
    - family: Noore
      fonts:
        - asset: fonts/Noore.ttf
    - family: Kurale
      fonts:
        - asset: fonts/Kurale.otf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf 
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

flutter_native_splash:
  color: '#ffffff'
  image_path: assets/img/app_icon.png