name: muslim_today
description: A new Flutter project.

version: 1.4.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  apple_sign_in_safety: ^0.0.6
  audioplayers: ^4.1.0
  auto_size_text: ^3.0.0
  card_swiper: ^2.0.3
  change_app_package_name: ^1.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.4
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.1.2+1
  flutter_qiblah: ^2.0.2
  flutter_svg: ^2.0.7
  flutter_vibrate: ^1.3.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  get: ^4.6.1
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.4
  hijri: ^3.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  ionicons: ^0.2.2
  package_info: ^2.0.2
  package_info_plus: ^4.0.2
  path: ^1.8.0
  path_provider: ^2.0.11
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.2
  quran: ^1.1.2
  share: ^2.0.4
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  swipe: ^0.0.1
  syncfusion_flutter_gauges: ^22.1.34
  theme_tailor_annotation: ^2.0.0
  url_launcher: ^6.0.20

dependency_overrides: null

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  theme_tailor: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/

  fonts:
    
    - family: Noore
      fonts:
        - asset: fonts/Noore.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf

flutter_native_splash:
  color: "#ffffff"
  image_path: assets/img/app_icon.png
